In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import pickle

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/densaiko/data_science_learning/main/dataset/Human%20Capital.csv')
df

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,0,49.0,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,60.0,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,50.0,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,50.0,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,73.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54803,3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,78.0,0
54804,74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,56.0,0
54805,13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,0,79.0,0
54806,13614,Sales & Marketing,region_9,NaN,m,sourcing,1,29,1.0,2,0,NaN,0
54807,51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,49.0,0

In [3]:
# kalau ada missing value, hapus saja barisnya :)
df = df.dropna()
df

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,0,49.0,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,60.0,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,50.0,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,50.0,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,73.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54802,6915,Sales & Marketing,region_14,Bachelor's,m,other,2,31,1.0,2,0,49.0,0
54803,3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,78.0,0
54804,74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,56.0,0
54805,13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,0,79.0,0
54807,51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,49.0,0

EDA sederhana

In [4]:
df['department'].value_counts()

department
Sales & Marketing    13711
Operations            9259
Procurement           6639
Technology            6502
Analytics             4610
HR                    2060
Finance               1941
R&D                    893
Legal                  765
Name: count, dtype: int64

In [5]:
df['region'].value_counts()

region
region_2     10288
region_22     5171
region_7      4200
region_15     2373
region_13     2355
region_26     1867
region_31     1617
region_4      1541
region_27     1355
region_16     1260
region_11     1130
region_28     1093
region_23     1051
region_29      852
region_19      788
region_20      746
region_14      738
region_32      728
region_17      721
region_25      693
region_5       674
region_10      601
region_30      571
region_8       545
region_6       544
region_1       537
region_24      449
region_12      391
region_21      349
region_9       318
region_3       313
region_33      256
region_34      242
region_18       23
Name: count, dtype: int64

In [6]:
df['gender'].value_counts()

gender
m    32347
f    14033
Name: count, dtype: int64

In [7]:
df['education'].value_counts()

education
Bachelor's          31767
Master's & above    14194
Below Secondary       419
Name: count, dtype: int64

In [8]:
df['recruitment_channel'].value_counts()

recruitment_channel
other       25747
sourcing    19655
referred      978
Name: count, dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46380 entries, 0 to 54807
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           46380 non-null  int64
 1   department            46380 non-null  object
 2   region                46380 non-null  object
 3   education             46380 non-null  object
 4   gender                46380 non-null  object
 5   recruitment_channel   46380 non-null  object
 6   no_of_trainings       46380 non-null  int64
 7   age                   46380 non-null  int64
 8   previous_year_rating  46380 non-null  float64
 9   length_of_service     46380 non-null  int64
 10  awards_won            46380 non-null  int64
 11  avg_training_score    46380 non-null  float64
 12  is_promoted           46380 non-null  int64
dtypes: float64(2), int64(6), object(5)
memory usage: 5.0+ MB

In [11]:
#Target Value
#Data masih imbalance namun dibiarkan saja karna akan mencoba data asli
df['is_promoted'].value_counts()

is_promoted
0    42309
1     4071
Name: count, dtype: int64

In [12]:
df.describe()

,employee_id,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted
count,46380.000000,46380.000000,46380.000000,46380.00000,46380.000000,46380.000000,46380.000000,46380.000000
mean,39191.504248,1.254506,35.572402,3.33232,6.307956,0.023502,63.927577,0.087775
std,22644.419549,0.607985,7.526501,1.25897,4.202143,0.151492,13.425576,0.282970
min,1.000000,1.000000,20.000000,1.00000,1.000000,0.000000,39.000000,0.000000
25%,19582.750000,1.000000,30.000000,3.00000,3.000000,0.000000,51.000000,0.000000
50%,39169.500000,1.000000,34.000000,3.00000,5.000000,0.000000,60.000000,0.000000
75%,58858.250000,1.000000,39.000000,4.00000,8.000000,0.000000,77.000000,0.000000
max,78298.000000,10.000000,60.000000,5.00000,37.000000,1.000000,99.000000,1.000000

Data Pre-Processing (sederhana)

In [13]:
#Copy Dataset
df_cp = df.copy()

In [14]:
#Urutkan index
df_cp = df_cp.reset_index(drop = True)
df_cp

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,0,49.0,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,60.0,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,50.0,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,50.0,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,73.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
46375,6915,Sales & Marketing,region_14,Bachelor's,m,other,2,31,1.0,2,0,49.0,0
46376,3030,Technology,region_14,Bachelor's,m,sourcing,1,48,3.0,17,0,78.0,0
46377,74592,Operations,region_27,Master's & above,f,other,1,37,2.0,6,0,56.0,0
46378,13918,Analytics,region_1,Bachelor's,m,other,1,27,5.0,3,0,79.0,0
46379,51526,HR,region_22,Bachelor's,m,other,1,27,1.0,5,0,49.0,0

In [15]:
df_cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46380 entries, 0 to 46379
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           46380 non-null  int64
 1   department            46380 non-null  object
 2   region                46380 non-null  object
 3   education             46380 non-null  object
 4   gender                46380 non-null  object
 5   recruitment_channel   46380 non-null  object
 6   no_of_trainings       46380 non-null  int64
 7   age                   46380 non-null  int64
 8   previous_year_rating  46380 non-null  float64
 9   length_of_service     46380 non-null  int64
 10  awards_won            46380 non-null  int64
 11  avg_training_score    46380 non-null  float64
 12  is_promoted           46380 non-null  int64
dtypes: float64(2), int64(6), object(5)
memory usage: 4.6+ MB

In [17]:
#Kumpulkan semua kolom kategorikal
#karena algoritma hanya dapat menerima numerikal
columns_cat = df_cp.select_dtypes(include = ['object']).columns.to_list()
columns_cat

['department', 'region', 'education', 'gender', 'recruitment_channel']

kita gunakan encoder untuk merubah kategorikal menjadi numerikal

In [18]:
label_encoders = {} # dictionary untuk menyimpan kumpulan encoder dari kolom2 categorical

for col in columns_cat:
  label_encoder = LabelEncoder() # buat objek label encoder untuk setiap kolom categorical
  label_encoder.fit(df_cp[col]) # label encoder melakukan training untuk isi kolom kategorical
  df_cp[col] = label_encoder.transform(df_cp[col]) # label encoder melakukan transformasi, timpa isi kolom tsb sebelumnya
  label_encoders[col] = label_encoder # simpan objek encoder di dictionary
  pickle.dump(label_encoder, open('label_encoder_' + col + '.pkl', 'wb')) # simpan dalam file pickle di server gcolab

In [19]:
df_cp

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,awards_won,avg_training_score,is_promoted
0,65438,7,31,2,0,2,1,35,5.0,8,0,49.0,0
1,65141,4,14,0,1,0,1,30,5.0,4,0,60.0,0
2,7513,7,10,0,1,2,1,34,3.0,7,0,50.0,0
3,2542,7,15,0,1,0,2,39,1.0,10,0,50.0,0
4,48945,8,18,0,1,0,1,45,3.0,2,0,73.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
46375,6915,7,5,0,1,0,2,31,1.0,2,0,49.0,0
46376,3030,8,5,0,1,2,1,48,3.0,17,0,78.0,0
46377,74592,4,19,2,0,0,1,37,2.0,6,0,56.0,0
46378,13918,0,0,0,1,0,1,27,5.0,3,0,79.0,0
46379,51526,2,14,0,1,0,1,27,1.0,5,0,49.0,0

In [20]:
#Drop kolom yang tidak sesuai
X = df_cp.drop(columns = ['employee_id', 'is_promoted'])
y = df_cp['is_promoted'] #kolom target

In [21]:
#Split data set untuk training 80% dan testing 20% dan melakukan pemisahan data random
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 32)

**ML Modelling**

In [22]:
logreg = LogisticRegression() # buat objek logistic regression

In [23]:
logreg

LogisticRegression()

In [24]:
#membuat model Log Reg
model_logreg = logreg.fit(X_train, y_train)

In [25]:
y_pred_train = model_logreg.predict(X_train)
y_pred_test = model_logreg.predict(X_test)

In [26]:
training_acc = accuracy_score(y_train, y_pred_train)
test_acc = accuracy_score(y_test, y_pred_test)

Check Score Akurasi

In [27]:
print('training accuracy:', training_acc)
print('testing accuracy:', test_acc)

training accuracy: 0.9150226390685641
testing accuracy: 0.9149417852522639

In [ ]:
pickle.dump(model_logreg, open('model_logreg.pkl', 'wb'))

**Membuat Backend API menggunakan framework Flask**

In [ ]:
!pip install Flask==3.0.0 pyngrok==7.1.2

Collecting Flask==3.0.0
  Downloading flask-3.0.0-py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.7/99.7 kB 1.9 MB/s eta 0:00:00
Collecting pyngrok==7.1.2
  Downloading pyngrok-7.1.2-py3-none-any.whl (22 kB)
Requirement already satisfied: Werkzeug>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from Flask==3.0.0) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.2 in /usr/local/lib/python3.10/dist-packages (from Flask==3.0.0) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.10/dist-packages (from Flask==3.0.0) (2.2.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.10/dist-packages (from Flask==3.0.0) (8.1.7)
Collecting blinker>=1.6.2 (from Flask==3.0.0)
  Downloading blinker-1.8.2-py3-none-any.whl (9.5 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.10/dist-packages (from pyngrok==7.1.2) (6.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=3.1.2->Flask==3.0.0) (2.1.5)
Installing collected packages: pyngrok, blinker, Flask
  Attempting uninstall: blinker
    Found existing installation: blinker 1.4
ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

In [ ]:
ngrok_key = '2bhzCvqoi1lEflosLFdyu193kZy_6vPYgud219KPEVnhtDdkd'
port = 4999

In [ ]:
from pyngrok import ngrok

In [ ]:
ngrok.set_auth_token(ngrok_key)
ngrok.connect(port).public_url

'https://901b-34-48-72-87.ngrok-free.app'

In [ ]:
from flask import Flask, jsonify, request
from json import JSONEncoder

In [ ]:
app = Flask(__name__)

@app.route('/', methods = ['GET'])
def index():
  return jsonify({'berhasil':1})

@app.route('/predict', methods = ['GET'])
def predict():
  data = request.json
  df_new = pd.DataFrame(data, index = [0])

  with open('/content/label_encoder_department.pkl', 'rb') as file:
    label_encoder_department = pickle.load(file)
  with open('/content/label_encoder_education.pkl', 'rb') as file:
    label_encoder_education = pickle.load(file)
  with open('/content/label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)
  with open('/content/label_encoder_recruitment_channel.pkl', 'rb') as file:
    label_encoder_recruitment_channel = pickle.load(file)
  with open('/content/label_encoder_region.pkl', 'rb') as file:
    label_encoder_region = pickle.load(file)

  df_new['department'] = label_encoder_department.transform(df_new['department'])
  df_new['education'] = label_encoder_education.transform(df_new['education'])
  df_new['gender'] = label_encoder_gender.transform(df_new['gender'])
  df_new['recruitment_channel'] = label_encoder_recruitment_channel.transform(df_new['recruitment_channel'])
  df_new['region'] = label_encoder_region.transform(df_new['region'])

  # load modelnya untuk prediksi
  with open('/content/model_logreg.pkl', 'rb') as file:
    model_logreg = pickle.load(file)

  y_pred = model_logreg.predict(df_new)

  return jsonify({'status prediksi':'berhasil', 'is_promoted': y_pred.tolist()})

if __name__ == '__main__':
  app.run(port = 4999)

 * Serving Flask app '__main__'
 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:4999
INFO:werkzeug:Press CTRL+C to quit
ERROR:__main__:Exception on /predict [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-42-b082f919a625>", line 33, in predict
    y_pred = model_logreg.predict(df_new)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_base.py", line 419, in predict
    scores = self.decision_function(X)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_base.py", line 400, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 548, in _validate_data
    self._check_feature_names(X, reset=reset)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 481, in _check_feature_names
    raise ValueError(message)
ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- tambahan

INFO:werkzeug:127.0.0.1 - - [05/Jun/2024 14:10:49] "GET /predict HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [05/Jun/2024 14:12:39] "GET /predict HTTP/1.1" 200 -

In [ ]:
# data untuk coba2 di postman
data = {
    "department": "Operations",
    "region": "region_7",
    "education": "Master's & above",
    "gender": "f",
    "recruitment_channel": "sourcing",
    "no_of_trainings": 1,
    "age": 35,
    "previous_year_rating": 5.0,
    "length_of_service": 8,
    "awards_won": 0,
    "avg_training_score": 49.0
}